"""Add first_login column

Revision ID: 1ecd8510b254
Revises: 0cad8ec34fd0
Create Date: 2025-07-06 09:06:54.406503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecd8510b254'
down_revision = '0cad8ec34fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_login', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.drop_column('first_login')

    # ### end Alembic commands ###
